"""/start — register a new user, reactivate + refresh a returning one (nudging them to renew if
their trial/paid access has expired), or — when reached via a deep-link payload — one of two
different linking flows:
  - `t.me/<bot>?start=ref_xxxxxx` (dorin_common/channel_link.py), generated on the website's
    /account page: links THIS Telegram account to that SAME existing user instead of creating a
    separate one. See website/whatsapp_webhook.py for the WhatsApp side of the same feature.
  - `t.me/<bot>?start=gl_xxxxx` (dorin_common/google_link.py), generated by
    website/main.py's auth_google_callback when a Google sign-in has nowhere to go yet: attaches
    that pending google_sub to whichever user this /start resolves to (new or existing) — entirely
    server-side, so it doesn't matter which browser/app the visitor is in when they get here. See
    that module's own docstring for why this exists (Telegram's in-app browser is a separate
    cookie jar from wherever the Google sign-in started).
"""
from __future__ import annotations

import asyncio
import logging
import os

from config import WEBSITE_URL
from dorin_common.access import has_full_access
from dorin_common.channel_link import CODE_PREFIX as CHANNEL_LINK_CODE_PREFIX
from dorin_common.channel_link import resolve_link_code
from dorin_common.db import get_session
from dorin_common.google_link import TOKEN_PREFIX as GOOGLE_LINK_TOKEN_PREFIX
from dorin_common.google_link import resolve_google_link_token
from dorin_common.models import User
from sqlalchemy import select
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger(__name__)

# Mirrors website/main.py's _is_owner_id — same secret, same "owner always has full access"
# override, kept in its own module-level var here rather than in config.py since (like
# handlers/support.py's own copy) only this one handler needs it.
OWNER_TELEGRAM_USER_ID = os.environ.get("OWNER_TELEGRAM_USER_ID")

WELCOME = (
    "✨ 🏠 היי {name}! אני בוט חיפוש דירות אישי — סורק את שוק הדירות ומודיע לך כשמופיעה דירה "
    "שמתאימה לסינון שלך.\n\n"
    "פקודות:\n"
    "/filter — הגדרת/עדכון הסינון שלך\n"
    "/apartments — הדירות התואמות האחרונות\n"
    "/liked — הדירות ששמרת\n"
    "/profile — הפרופיל וההגדרות שלך\n\n"
    "רוצה גם להתחבר באתר (Google/ווטסאפ)? {account_url} 🔗"
)

LINKED = "🎉 חיברתי! אתה כבר רשום ומעודכן אצלי במערכת — מעכשיו תקבל עדכונים גם כאן בטלגרם."

LINK_CONFLICT = (
    "לחשבון הטלגרם הזה כבר יש חשבון נפרד אצלי, אז אי אפשר לחבר אותו לחשבון אחר. "
    "אם זו טעות, כתוב/י לנו דרך /contact."
)

# Prepended to the normal reply when a pending Google sign-in (gl_ deep-link token) got attached
# to this user right here, right now — see google_link.py's module docstring for why this whole
# mechanism exists.
GOOGLE_LINKED_NOTE = (
    "🔗 חשבון ה-Google שלך קושר בהצלחה לחשבון הזה — מעכשיו אפשר להתחבר איתו באתר, מכל דפדפן.\n\n"
)

# 2026-09-04 — matches the reference product's own confirmed /start behavior for a returning user
# whose trial/paid access has expired (screenshotted live): a personalized nudge naming their own
# search cities, instead of the plain welcome, pointing straight at /upgrade.
RENEWAL_NEEDED = (
    "היי {name}! 👋 שוב אנחנו?\n\n"
    "שמתי לב שתקופת הגישה שלך הסתיימה, אז ההתראות מושהות כרגע. "
    "{cities_line}רוצה שנחדש את המנוי ונחזור לחפש לך דירה? אפשר ישר כאן: {upgrade_url} 🔥🏠"
)


def _format_cities_he(cities: list[str]) -> str:
    """"ירושלים, הר גילה ומבשרת ציון" — a natural-Hebrew join, not just a comma list."""
    if not cities:
        return ""
    if len(cities) == 1:
        return cities[0]
    return ", ".join(cities[:-1]) + " ו" + cities[-1]


def _upsert_or_link_user_sync(tg_user, start_payload: str | None) -> tuple[str, str]:
    """Returns (outcome, reply_text). outcome is "linked" / "conflict" / "normal" / "expired" —
    tests key off outcome; start() just sends reply_text as-is.

    `start_payload` is whatever followed `?start=` in the deep link, if any — dispatched by prefix
    since it can be either kind of token (never both at once, the two prefixes don't collide):
    a channel_link_code (`ref_...`, attaches THIS Telegram account to an existing user) or a
    google_link_token (`gl_...`, attaches a pending Google sign-in to whichever user this /start
    resolves to). A plain "/start" with no payload leaves both None and hits the normal path."""
    is_owner = bool(OWNER_TELEGRAM_USER_ID) and str(tg_user.id) == str(OWNER_TELEGRAM_USER_ID)
    link_code = (
        start_payload
        if start_payload and start_payload.startswith(CHANNEL_LINK_CODE_PREFIX)
        else None
    )
    google_link_token = (
        start_payload if start_payload and start_payload.startswith(GOOGLE_LINK_TOKEN_PREFIX) else None
    )

    with get_session() as session:
        if link_code:
            code_user = resolve_link_code(session, link_code)
            if code_user is not None:
                existing = session.scalar(
                    select(User).where(User.telegram_user_id == tg_user.id)
                )
                if existing is not None and existing.id != code_user.id:
                    # This Telegram account already has its OWN separate account — linking it to
                    # a second one would mean merging two rows' filters/history, which we don't
                    # do automatically. Leave both accounts exactly as they were.
                    return "conflict", LINK_CONFLICT
                code_user.telegram_user_id = tg_user.id
                code_user.telegram_username = tg_user.username
                code_user.first_name = code_user.first_name or tg_user.first_name
                code_user.is_active = True
                session.commit()
                return "linked", LINKED
            # Unknown/expired code — fall through to the normal /start handling below rather
            # than erroring, since a plain "/start" with no payload hits this same path with
            # link_code=None every time.

        # Consumed BEFORE the user upsert below so it's single-use regardless of which branch
        # (new user vs. reactivate) ends up applying it.
        pending_google_sub = (
            resolve_google_link_token(session, google_link_token) if google_link_token else None
        )

        user = session.scalar(select(User).where(User.telegram_user_id == tg_user.id))
        is_new = user is None
        if is_new:
            user = User(
                telegram_user_id=tg_user.id,
                telegram_username=tg_user.username,
                first_name=tg_user.first_name,
            )
            session.add(user)
        else:
            # reactivate — mirrors the reference bot re-engaging a paused/"found apartment" user
            user.is_active = True
            user.telegram_username = tg_user.username
            user.first_name = tg_user.first_name
        session.commit()

        # Don't silently overwrite an existing DIFFERENT Google link — same guard website/main.py's
        # auth_google_callback already applies for its own session_user_id fallback.
        google_linked_now = False
        if pending_google_sub and user.google_sub is None:
            user.google_sub = pending_google_sub
            session.commit()
            google_linked_now = True
        note = GOOGLE_LINKED_NOTE if google_linked_now else ""

        if is_new:
            return "normal", note + WELCOME.format(
                name=tg_user.first_name or "",
                account_url=f"{WEBSITE_URL}/account?uid={tg_user.id}",
            )

        # Only a returning user who already onboarded (has a filter) can have "expired" access in
        # any meaningful sense — a brand-new row never reaches here (handled above), and someone
        # mid-onboarding with no filter yet is always still within their fresh trial window.
        if user.filter is not None and not has_full_access(user, is_owner=is_owner):
            cities = _format_cities_he(user.filter.cities)
            reply = RENEWAL_NEEDED.format(
                name=tg_user.first_name or "",
                cities_line=f"מתגעגע/ת לעדכונים על {cities}? " if cities else "",
                upgrade_url=f"{WEBSITE_URL}/upgrade?uid={tg_user.id}",
            )
            return "expired", note + reply

        return "normal", note + WELCOME.format(
            name=tg_user.first_name or "",
            account_url=f"{WEBSITE_URL}/account?uid={tg_user.id}",
        )


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    tg_user = update.effective_user
    start_payload = context.args[0] if context.args else None
    logger.info(
        "/start invoked by telegram_user_id=%s (start_payload=%s)", tg_user.id, bool(start_payload)
    )
    # asyncio.to_thread so a slow/blocking DB round-trip doesn't freeze the whole bot - PTB
    # processes updates one at a time by default (max_concurrent_updates=1, see main.py), so a
    # synchronous DB call made directly on the event loop blocks every OTHER user's button press
    # and command for its entire duration, not just this one. See PROJECT_STATE.md's 2026-08-31
    # "bot-wide blocking DB calls" entry for the investigation that found this.
    _outcome, reply_text = await asyncio.to_thread(
        _upsert_or_link_user_sync, tg_user, start_payload
    )
    await update.message.reply_text(reply_text)
