"""Tests for bot/handlers/start.py's OTHER linking path: a `gl_xxxxx` payload from a
`t.me/<bot>?start=gl_xxxxx` deep link generated by website/main.py's auth_google_callback when a
Google sign-in has nowhere to go yet (see dorin_common/google_link.py's own docstring for why this
exists — completes entirely server-side, not dependent on which browser/app the visitor is in).

Same _QueuedScalarSession pattern as test_start_channel_link.py (see that file's own comment).
"""
from __future__ import annotations

import os
from types import SimpleNamespace
from unittest.mock import patch

os.environ.setdefault("DATABASE_URL", "postgresql://unused/unused")

import handlers.start as start_module


class _QueuedScalarSession:
    def __init__(self, results):
        self._results = list(results)
        self.committed = False

    def scalar(self, stmt):
        return self._results.pop(0) if self._results else None

    def add(self, obj):
        pass

    def commit(self):
        self.committed = True

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        return False


def _tg_user(id=555, username="amirt", first_name="Amir"):
    return SimpleNamespace(id=id, username=username, first_name=first_name)


def test_valid_token_links_google_sub_to_a_brand_new_user():
    session = _QueuedScalarSession(results=[None])  # no existing telegram_user_id row
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token", lambda s, tok: "google-sub-1"),
    ):
        outcome, reply = start_module._upsert_or_link_user_sync(_tg_user(), "gl_abc123")

    assert outcome == "normal"
    assert reply.startswith(start_module.GOOGLE_LINKED_NOTE)
    assert start_module.WELCOME.format(
        name="Amir", account_url="https://todira.duckdns.org/account?uid=555"
    ) in reply
    assert session.committed is True


def test_valid_token_links_google_sub_to_an_existing_unlinked_user():
    user = SimpleNamespace(
        id=2, telegram_user_id=555, telegram_username="amirt", first_name="Amir",
        is_active=False, filter=None, google_sub=None,
    )
    session = _QueuedScalarSession(results=[user])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token", lambda s, tok: "google-sub-2"),
    ):
        outcome, reply = start_module._upsert_or_link_user_sync(_tg_user(), "gl_abc123")

    assert outcome == "normal"
    assert user.google_sub == "google-sub-2"
    assert reply.startswith(start_module.GOOGLE_LINKED_NOTE)


def test_valid_token_does_not_overwrite_an_existing_different_google_link():
    user = SimpleNamespace(
        id=2, telegram_user_id=555, telegram_username="amirt", first_name="Amir",
        is_active=False, filter=None, google_sub="already-linked-sub",
    )
    session = _QueuedScalarSession(results=[user])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token", lambda s, tok: "google-sub-new"),
    ):
        outcome, reply = start_module._upsert_or_link_user_sync(_tg_user(), "gl_abc123")

    assert outcome == "normal"
    assert user.google_sub == "already-linked-sub"  # untouched
    assert not reply.startswith(start_module.GOOGLE_LINKED_NOTE)
    assert reply == start_module.WELCOME.format(
        name="Amir", account_url="https://todira.duckdns.org/account?uid=555"
    )


def test_expired_or_unknown_token_falls_through_with_no_note():
    session = _QueuedScalarSession(results=[None])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token", lambda s, tok: None),
    ):
        outcome, reply = start_module._upsert_or_link_user_sync(_tg_user(), "gl_expired")

    assert outcome == "normal"
    assert reply == start_module.WELCOME.format(
        name="Amir", account_url="https://todira.duckdns.org/account?uid=555"
    )


def test_plain_start_never_calls_resolve_google_link_token():
    session = _QueuedScalarSession(results=[None])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token") as resolve_mock,
    ):
        start_module._upsert_or_link_user_sync(_tg_user(), None)

    resolve_mock.assert_not_called()


def test_channel_link_code_payload_never_calls_resolve_google_link_token():
    code_user = SimpleNamespace(
        id=9, telegram_user_id=None, telegram_username=None, first_name=None, is_active=False,
    )
    session = _QueuedScalarSession(results=[None])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_link_code", lambda s, code: code_user),
        patch.object(start_module, "resolve_google_link_token") as resolve_mock,
    ):
        outcome, _reply = start_module._upsert_or_link_user_sync(_tg_user(), "ref_abc123")

    assert outcome == "linked"
    resolve_mock.assert_not_called()


def test_google_linked_note_is_prepended_before_the_renewal_nudge_too():
    import datetime as dt

    now = dt.datetime.now(dt.timezone.utc)
    user = SimpleNamespace(
        id=2, telegram_user_id=555, telegram_username="amirt", first_name="Amir",
        is_active=False, filter=SimpleNamespace(cities=["חיפה"]), google_sub=None,
        trial_ends_at=now - dt.timedelta(days=1), paid_until=None, free_access_granted=False,
    )
    session = _QueuedScalarSession(results=[user])
    with (
        patch.object(start_module, "get_session", lambda: session),
        patch.object(start_module, "resolve_google_link_token", lambda s, tok: "google-sub-3"),
    ):
        outcome, reply = start_module._upsert_or_link_user_sync(_tg_user(), "gl_abc123")

    assert outcome == "expired"
    assert reply.startswith(start_module.GOOGLE_LINKED_NOTE)
    assert "חיפה" in reply
    assert user.google_sub == "google-sub-3"
