"""initial schema: users, filters, listings, sent_notifications, user_listing_actions

Hand-authored to match common/dorin_common/models.py (plan Section 2) rather than
autogenerated, since there was no live DB available to diff against yet. Revisit with
`alembic revision --autogenerate` for the next schema change once this baseline is applied.

Revision ID: 0001_initial_schema
Revises:
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "notifications_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.create_index("ix_users_telegram_user_id", "users", ["telegram_user_id"], unique=True)

    op.create_table(
        "filters",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("deal_type", sa.Text(), server_default="rent", nullable=False),
        sa.Column(
            "property_types", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("cities", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "neighborhoods_include",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "neighborhoods_exclude",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "streets_include", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "streets_exclude", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("price_min", sa.Integer(), nullable=True),
        sa.Column("price_max", sa.Integer(), nullable=True),
        sa.Column("require_price", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rooms_min", sa.Numeric(3, 1), nullable=True),
        sa.Column("rooms_max", sa.Numeric(3, 1), nullable=True),
        sa.Column("floor_min", sa.Integer(), nullable=True),
        sa.Column("floor_max", sa.Integer(), nullable=True),
        sa.Column(
            "ground_floor_only", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_parking", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_elevator", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_balcony", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_pets_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_renovated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_has_photos", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "require_roommate_friendly",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("safe_room_pref", sa.Text(), server_default="any", nullable=False),
        sa.Column("furniture_pref", sa.Text(), server_default="any", nullable=False),
        sa.Column("min_area_sqm", sa.Integer(), nullable=True),
        sa.Column("no_brokers", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "flexible_match", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("move_in_earliest", sa.Date(), nullable=True),
        sa.Column("move_in_latest", sa.Date(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index("ix_filters_user_id", "filters", ["user_id"], unique=True)
    op.create_index("ix_filters_cities_gin", "filters", ["cities"], postgresql_using="gin")

    op.create_table(
        "listings",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("deal_type", sa.Text(), nullable=False),
        sa.Column("property_type", sa.Text(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("rooms", sa.Numeric(3, 1), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("floor_total", sa.Integer(), nullable=True),
        sa.Column("size_sqm", sa.Integer(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("neighborhood", sa.Text(), nullable=True),
        sa.Column("street", sa.Text(), nullable=True),
        sa.Column("has_parking", sa.Boolean(), nullable=True),
        sa.Column("has_elevator", sa.Boolean(), nullable=True),
        sa.Column("has_balcony", sa.Boolean(), nullable=True),
        sa.Column("pets_allowed", sa.Boolean(), nullable=True),
        sa.Column("is_renovated", sa.Boolean(), nullable=True),
        sa.Column("is_roommate_friendly", sa.Boolean(), nullable=True),
        sa.Column("safe_room_type", sa.Text(), nullable=True),
        sa.Column("furniture", sa.Text(), nullable=True),
        sa.Column("is_broker_listing", sa.Boolean(), nullable=True),
        sa.Column("move_in_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "image_urls", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scraped_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_delisted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("delisted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=True),
        sa.UniqueConstraint("source", "external_id", name="uq_listings_source_external_id"),
    )
    op.create_index("ix_listings_source", "listings", ["source"])
    op.create_index("ix_listings_deal_type", "listings", ["deal_type"])
    op.create_index("ix_listings_city", "listings", ["city"])
    op.create_index("ix_listings_scraped_at", "listings", ["scraped_at"])

    op.create_table(
        "sent_notifications",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.BigInteger(),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), server_default="new", nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.UniqueConstraint(
            "user_id", "listing_id", "reason", name="uq_sent_notifications_user_listing_reason"
        ),
    )

    op.create_table(
        "user_listing_actions",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "listing_id",
            sa.BigInteger(),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.UniqueConstraint("user_id", "listing_id", "action", name="uq_user_listing_actions"),
    )


def downgrade() -> None:
    op.drop_table("user_listing_actions")
    op.drop_table("sent_notifications")
    op.drop_index("ix_listings_scraped_at", table_name="listings")
    op.drop_index("ix_listings_city", table_name="listings")
    op.drop_index("ix_listings_deal_type", table_name="listings")
    op.drop_index("ix_listings_source", table_name="listings")
    op.drop_table("listings")
    op.drop_index("ix_filters_cities_gin", table_name="filters")
    op.drop_index("ix_filters_user_id", table_name="filters")
    op.drop_table("filters")
    op.drop_index("ix_users_telegram_user_id", table_name="users")
    op.drop_table("users")
